# Generated by Django 6.0.3 on 2026-03-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_alter_audit_id_alter_finding_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
