# Generated by Django 4.2 on 2026-05-14 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audits", "0004_alter_audit_id_alter_finding_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                        ],
                        help_text="What action was performed (create, update, delete)",
                        max_length=10,
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Which fields changed: {'field_name': {'old': 'value1', 'new': 'value2'}}",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this change happened",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        help_text="Which audit this log entry is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="audits.audit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which user made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
